# ----
# Site

title: A Cut Above
url: "https://www.github.com/lukeprince20"
baseurl:
google_analytics_key:
newsletter_action:
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: images/rhinoceros-of-durer.png
description: Personal Blog
author:
  name: Luke Prince
  email: lukeprince20@gmail.com
  twitter: # twitter username without the @ symbol
social:
  name:
  links:

# -----
# Build

timezone: Etc/UTC

paginate: 10
paginate_path: "/:num/"
permalink: pretty

# ----------
# Conversion
markdown:    kramdown
highlighter: rouge

# -------------------
# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# -------
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      push_sidebar_down: true
      print_stylesheet: true
      comments: true
      _options:
        content:
          width: 1560
          height: 2000
        featured_image:
          width: 1560
          height: 2000
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
      push_sidebar_down: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
  - prev

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS

_options:
  author_image:
    width: 640
    height: 447
